### ISSUE TITLE
Mojave support

### ISSUE THREAD

**Issue by EETagent** [EETagent/T480-OpenCore-Hackintosh#11]
TODO: Recompile kexts for Mojave.

**Comment by afreuden** [comment]
Hi @EETagent,

I may be able to assist with this. I am currently running 10.14 using release 3.3.3 on my T480 for last couple of days. 

I don’t have the capacity to test everything but other than a very small chance where the TrackPoint and TouchPad are unresponsive from a cold boot and the Intel wifi and Bluetooth is unresponsive after waking from sleep everything on Mojave is good so far!

**Comment by EETagent** [comment]
@afreuden 

I opened this as I am not really sure which kexts are currently targeted for 10.15 only. I compiled few of those but I probably alredy replaced them with newer versions from internet which should be for Mojave too. Great to hear that everything works fine

>  a very small chance where the TrackPoint and TouchPad are unresponsive

That is a issue with latest VoodooSMBus or VoodooRMI ( Or both? ). These issues did not appear with VoodooRMI 0.2.0. I first encountered it with version 0.3.0 and reported it, because this problem became so rare and I did not have really a time to endlessly reboot and gather logs with Debug version, I let it be. I will compile latest 0.5.0 and check if this problem still persist.

> Intel wifi and Bluetooth is unresponsive after waking from sleep

Please try newest version from master, there is latest release of itlwm driver and HeliPort software  ( Which is now reallz usable ).

**Comment by EETagent** [comment]
@afreuden 
> Intel wifi and Bluetooth is unresponsive after waking from sleep

Latest release of IntelBluetoothFirmware ( 3 hours ago ) probably fixed your BT issues after wake. Please try latest changes in master

-  fix wakeup crash issue.
-  fix wakeup BT unavailable issue.

**Comment by afreuden** [comment]
Hi @EETagent 

Thanks for the update, I will test these and report back when I can. I realise my initial post on what is working and what isn’t on 10.14.6 was a bit vague so I will test as many items as a I can and update this post.

Angus

**Comment by EETagent** [comment]
Hi @afreuden,

can you please test latest build in master? I build few important kexts with macOS 10.15 SDK and would like to hear if it works. Otherwise I would download 10.14 SDK file and recompile them. Thanks

**Comment by afreuden** [comment]
Hey @EETagent,

I'll update my EFI with the current master and get back to you.

**Comment by EETagent** [comment]
Hi @afreuden,

can you please test latest master ( Which would become 4.0.0 release ), so I can close this issue?

Thanks for help
