### ISSUE TITLE
Latest kexts

### ISSUE THREAD

**Issue by EETagent** [EETagent/T480-OpenCore-Hackintosh#12]
TODO: Compile latest version of itlwm and HeliPort, VoodooSMBus and VoodooRMI, VoodooPS2Controller, NVMeFix, AppleALC, CPUFriend, HibernationFixup, RTCMemoryFixup, VirtualSMC, Lilu and WEG

**Comment by zombillano** [comment]
Some of those kext can be found at the OpenCore Vanilla Guide recommended [ Kext repo ](http://kexts.goldfish64.com/). ITLWm and HeliPort compiled kext can be found at their [gitter chat](https://gitter.im/OpenIntelWireless/itlwm). Anyway, I believe that it'd be better to have a testing brench for that and stick with stable releases on the master (just suggesting).

**Comment by EETagent** [comment]
> Some of those kext can be found at the OpenCore Vanilla Guide recommended [ Kext repo ](http://kexts.goldfish64.com/). 

Yep, that is where I got few updated kexts for this OC 0.6.0 update. Many kexts are missing there though and is still better to compile everything myself. It will take a while as I am not currently at home at my xcode machine and disk of my TP is so full that I can't justify downloading another 10 GB. 

> ITLWm and HeliPort compiled kext can be found at their [gitter chat](https://gitter.im/OpenIntelWireless/itlwm). 

Did not know that, nice find. From now, I will get HeliPort from there. It is still better to build own version with https://github.com/zxystd/HeliPort/pull/37 included though.

> Anyway, I believe that it'd be better to have a testing brench for that and stick with stable releases on the master (just suggesting).

I don't currently see any problem with it. Even OC 0.6.0 is at least in configuration minor change. If there will be problems, I will create preview branch. For now, tested stable builds will be released in releases and latest progress would be for those who clone master.

**Comment by EETagent** [comment]
Kexts are up to date for Big Sur
