### ISSUE TITLE
Big Sur announcement

### ISSUE THREAD

**Issue by EETagent** [EETagent/T480-OpenCore-Hackintosh#13]
To all people who would like to test Big Sur:

EDIT: See https://dortania.github.io/OpenCore-Desktop-Guide/extras/big-sur/

**Comment by EETagent** [comment]
**UPDATE**: https://www.reddit.com/r/hackintosh/comments/hn4eom/no_clone_install_of_big_sur_on_ryzen_opencore_060/

Looks like problem with kext injection during installation is fixed now. When I update OC and required kexts, Big Sur could be installed normally.

**Comment by fabiandiez** [comment]
Have you had the chance to try out Big Sur?
If so, would you recommend it (as in, is it stable) from your experience so far?

Anyways, thanks for the update!

**Comment by EETagent** [comment]
No, I still do not have time to update kexts and push newer version of OC. Friend runs Big Sur on his MBP 2015 and his experience is pretty good so far ( Except the installation, that was horrible even on Apple machine) I tried to download installer just after the keynote on MBA and it was not possible as it was awfully slow and it stopped all the time ( Definitely not an internet issue, There was a lot of interest in Big Sur )

**Comment by EETagent** [comment]
**UPDATE2** I pushed latest OC and kexts versions for Big Sur installator support e4a77e5. Do not forget to edit config.plist as described above. It should be possible to update from Catalina just like on a real Mac.

**Comment by EETagent** [comment]
**UPDATE3:** Installed Big Sur on a second partition. It runs great, what one can expect from developer beta. They should not change naming though as it is not complete overhaul like change from Classic was. I recently installed Snow Leopard ( It is possible, Google it :) ) on a old PowerMac G5 and one can se how little has this OS changed from user perspective since then. 
![Snímek obrazovky 2020-08-10 v 21 03 32](https://user-images.githubusercontent.com/20557318/89822151-053d6e00-db50-11ea-87c4-cf68f060ee36.png)

**Comment by EETagent** [comment]
As Big Sur is now pretty stable, there is no need for this issue.
