### ISSUE TITLE
HWPEnable instead of CPUFriend

### ISSUE THREAD

**Issue by EETagent** [EETagent/T480-OpenCore-Hackintosh#16]
![obrazek](https://user-images.githubusercontent.com/20557318/87290630-862c2a00-c4fe-11ea-9d11-91ea9a703015.png)

**Comment by zombillano** [comment]
I suggest you to give a look over this: https://github.com/tylernguyen/x1c6-hackintosh/issues/28

Maybe we can take some knowledge from there?

**Comment by EETagent** [comment]
@zombillano  This looks quite interesting
https://github.com/syscl/CPUTune
