### ISSUE TITLE
Add VoodooSMBus Maybe?

### ISSUE THREAD

**Issue by khokho** [EETagent/T480-OpenCore-Hackintosh#2]
Hello, 
I'm super new to hackintosh but I somehow managed to boot it up on my t480. I found you repo a bit too late but it's really a blessing. 💯 👍 
I found this kext: https://github.com/VoodooSMBus/VoodooSMBus which I tried to install but could figure out the .patch files and messed up the boot. So I'm just suggesting you to maybe try it.

**Comment by khokho** [comment]
The problem with current setup is when I have one finger in the middle of touchpad and I touch another one on left bottom corner, while releasing the on in the middle, the cursor jumps around. And it really drives on my nerves 😄 
And I hope I'll be fixed in VoodooSMBus

**Comment by EETagent** [comment]
@khokho  Thanks, it looks really interesting.

`00:1f.4 SMBus [0c05]: Intel Corporation Sunrise Point-LP SMBus [8086:9d23] (rev 21)`

T480 should be supported as its shares same SMBus with supported T480s.
I will look at it tomorrow or the day after tomorrow. PM981 is still giant mess and really unstable. I moved my ThinkPad to Fedora temporary because of that. As soon as I get Catalina on external drive again ( There are problems with sleep when running from USB drive. Does sleep work for you? ) and edit readme.

**Comment by khokho** [comment]
Thank you. I have 8086:9d23 as well.

Sleep works fine for me but I'm running on internal drive. So I can't help you with that one.

Only other problem I have is headphone jack start sounding weird at random times. 
I found this repo which mentions jack issues which I'm gonna try out. 
https://github.com/tienhuynh5312/ThinkPad-T480-Hackintosh

**Comment by khokho** [comment]
^ jack audio got fixed with above repo. But instead of running his provided "read and write.app", I executed:
`sudo mount -uw /`
then ./install.sh and reboot.

**Comment by khokho** [comment]
Oh, I see. Didn't notice that...

**Comment by khokho** [comment]
52a310a fixed my jumpy trackpad. All the gestures also seem to be much better! I also turned on the Tap to drag in accessibility and it's working like a charm.

**Comment by EETagent** [comment]
It is absolutely awesome. I am not going to merge it now to the master though as there are still issues with TrackPoint ( New version could fix that ) and longer boot times ( What for you? )

**Comment by khokho** [comment]
I feel like trackpoint is also better now but I don't use it so I might be wrong. 
And for boot time it feels the same. Booting from zero takes 17 seconds til opencore(which is a lot compared to linux bootloaders) and 37 seconds to login screen. But I think It was kind of same without VoodooSMBus. I'll test it soon.

**Comment by EETagent** [comment]
17 second until OC boot screen is really long.

**Comment by danny7g** [comment]
I opened an issue to discuss this and closed - sorry I missed this originally. 

I separately tested VoodooRMI and, yes, it's great.  There are a few timeout errors in the Verbose Bootlog causing extended boot time. I think it relates to the trackpad instructions in SSDT-KBRD-TP.aml in the ACPI folder. 

I've just tested this out within the last 30 minutes, so hopefully I'll be able to chase down the exact issue this weekend.

**Comment by EETagent** [comment]
Every TrackPad and TrackPoint settings was removed from SSDT-KBRD-TP ( Now only KBRD ). I removed also SSDT-SBUS as it can cause conflicts with VoodooSMBus

**Comment by khokho** [comment]
I don't think it's your issue but `DisableWhileTrackpoint=NO` does not allow touchpad with trackpoint. On the other hand it does work with trackpoint buttons(with `YES` touchpad was disabled everytime I pressed them). All my personal problems are solved but `DisableWhileTrackpoint=NO` does not work and neither does `DisableWhileTyping=NO`.

**Comment by khokho** [comment]
Also I just fixed my slow boot time to opencore with disabling CMS support.

**Comment by danny7g** [comment]
just posted this in the VoodoSMBus issues, too, but though i'd bring it here directly. 

i took a shot at recreating the the plist patches in opencore. opencore doesn't actually allow plist patching, but just blocks the kexts from loading. the patches go in the root -> kernel -> block section. the plist is very rough outside of this section, so i wouldn't use it for anything else.

[config.plist.zip](https://github.com/EETagent/T480-OpenCore-Hackintosh/files/4784265/config.plist.zip)
![Screen Shot 2020-06-15 at 9 49 28 PM](https://user-images.githubusercontent.com/65880975/84729930-1b64ee80-af52-11ea-8dc2-62faf37bb990.png)

**Comment by EETagent** [comment]
@danny7g  Thanks, I will ad them to the plist file.

**Comment by danny7g** [comment]
updated voodoosmbus from release version 2.0 
-removed Elan Trackpad support - gets rid of timeout on boot
-removes other smbus pci id listed (assuming we have the same pci id)

i also ended up just deleting those kexts blocked in the post above. 

[trackpad.zip](https://github.com/EETagent/T480-OpenCore-Hackintosh/files/4790266/trackpad.zip)

**Comment by EETagent** [comment]
@danny7g @khokho 

Are there any other issues? I am going to squash merge it soon.

**Comment by khokho** [comment]
Nope. Merge it

**Comment by EETagent** [comment]
Because VoodooSMBus and VoodooRMI are already in master, I am closing this issue.
