### ISSUE TITLE
New Intel Wi-Fi driver

### ISSUE THREAD

**Issue by EETagent** [EETagent/T480-OpenCore-Hackintosh#22]
Holy Moly, there is new driver in the works. It cooperate with itlwm and show itself as a Wi-Fi -> ThinkpadAssistant Wi-Fi switch should work. We should definitely try it. It can also be controlled natively without HeliPort.

https://github.com/usr-sse2/Black80211-Catalina

![obrazek](https://user-images.githubusercontent.com/20557318/89225181-162f3200-d5da-11ea-98ee-4a14ee0fecb3.png)

**Comment by swatchie-1** [comment]
Hi @EETagent thanks for making your cool opencore. I just obtained a T480 and am using your EFI. 
I tried this intel wifi method but it's unstable and when it wakes from sleep, the trackpad and trackpoint are disabled.
I'm using the native Apple airport card BCM943224PCIEBT2 and it's working well at the moment. Saves the headache.

**Comment by zombillano** [comment]
> Hi @EETagent thanks for making your cool opencore. I just obtained a T480 and am using your EFI.
> I tried this intel wifi method but it's unstable and when it wakes from sleep, the trackpad and trackpoint are disabled.
> I'm using the native Apple airport card BCM943224PCIEBT2 and it's working well at the moment. Saves the headache.
Itlwm + Heliport works fine for me. The driver mentioned over here is still on an early stage of development. Native Apple card is a good alternative, but I've found itlwm stable enough to stick with it and incidentally save some money.

**Comment by EETagent** [comment]
@zombillano  Yeah, that's why it is labeled as a low-priority enhancement. It seems stable but I would not use it until there is stable support for it in OpenCore ( Currently in itlwm branch )

**Comment by EETagent** [comment]
@zombillano  If you want to be a beta tester too, I just compiled and uploaded latest version of Black80211 and special version of itlwm in the Other folder. 

https://github.com/EETagent/T480-OpenCore-Hackintosh/tree/master/Other/Black80211

**Comment by zombillano** [comment]
> @zombillano If you want to be a beta tester too, I just compiled and uploaded latest version of Black80211 and special version of itlwm in the Other folder.
> 
> https://github.com/EETagent/T480-OpenCore-Hackintosh/tree/master/Other/Black80211

Is it stable? Right now I'm pretty happy with what I got on my T480 in terms of stability, which in fact is awesome because it doesn't break my productivity rate :P So I'd try it only if it doesn't have any major problem. If not I think I'd wait untill it gets at least as stable as the main itlwm branch.

**Comment by EETagent** [comment]
As a development of this kernel extension slowed down and it's  still not as stable as a pure itlwm with HeliPort, this issue can be closed for now.

**Comment by zombillano** [comment]
@EETagent give a look at the latest release of itlwm: https://github.com/OpenIntelWireless/itlwm/releases

BTW, do you have gitter? I'd like to talk to you in a more direct way, I've been thinking and investigating about a couple features that would be cool to implement.

**Comment by EETagent** [comment]
> @EETagent give a look at the latest release of itlwm: https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.1.0
> 

I compiled latest itlwm few days ago. It was just officiallyrelease now, no commit since then

> BTW, do you have gitter? I'd like to talk to you in a more direct way, I've been thinking and investigating about a couple features that would be cool to implement.

Yes, I have Gitter. Should I open room for this repository?

**Comment by zombillano** [comment]
> I compiled latest itlwm few days ago. It was just officially released now, no commit since then

So you are aware of the new AirportItlwm kext... Don't you think is awesome?

> Yes, I have Gitter. Should I open room for this repository?

I don't think so, I just want to talk about the possibility to add fan RPMs + basic Fan Speed Control + Adjustable battery threshold, which can be done via ACPI. It is quite late to me right now, so let me take a rest and I'll reach you via gitter tomorrow morning.

**Comment by EETagent** [comment]
> So you are aware of the new AirportItlwm kext... Don't you think is awesome?


Well, actually not. It's that some official version of Black80211-Catalina?

**Comment by zombillano** [comment]
> Well, actually not. It's that some official version of Black80211-Catalina?

Kind of, but this one is made by official OpenIntelWireless Team. I've been using it since yesterday and so far so good, give it a try, I think it will convince you.

**Comment by EETagent** [comment]
So I moved to AirportItlwm and loving it, still waiting though for WPA Enterprise support to access school Wi-FI differently than using HoRNDIS. It's bad though that there are different builds for every macOS version, hope that Acidantera's MacKernelSDK will fix these issues.

**Comment by zombillano** [comment]
> So I moved to AirportItlwm and loving it, still waiting though for WPA Enterprise support to access school Wi-FI differently than using HoRNDIS. It's bad though that there are different builds for every macOS version, hope that Acidantera's MacKernelSDK will fix these issues.

I've got back to itlwm just because I had several issues while having classes on zoom/classroom/etc/etc and a lot of interference when using bluetooth devices. Other than that I found it very very pleasant to use to navigate through the web, download files and see videos on youtube. I hope that they solve all these issues (and I'm pretty confident that they will, is just a matter of time).

**Comment by MrSlowSheep** [comment]
Is this faster than the drivers used for the GitHub? 
I get very slow download/upload speeds on WiFi right now. 
It is a driver problem as my WiFi speed was just fine while using Windows/Linux.

**Comment by zombillano** [comment]
> Is this faster than the drivers used for the GitHub?
> I get very slow download/upload speeds on WiFi right now.
> It is a driver problem as my WiFi speed was just fine while using Windows/Linux.

It isn't. This was a first implementation of native-like experience with itlwm kext as the base. Airportitlwm is the implementation made by itlwm developers. 

Itlwm and airportitlwm have a 50mbps download/15mbps upload limit, just because it only has 801.11n at 20Mhz implemented. I find itlwm to be more stable than airportitlwm at the moment

**Comment by MrSlowSheep** [comment]
> > Is this faster than the drivers used for the GitHub?
> > I get very slow download/upload speeds on WiFi right now.
> > It is a driver problem as my WiFi speed was just fine while using Windows/Linux.
> 
> It isn't. This was a first implementation of native-like experience with itlwm kext as the base. Airportitlwm is the equivalent implementation made by itlwm developers.
> 
> Itlwm and airportitlwm have a 50mbps download/15mbps upload limit, just because it only has 801.11n at 20Mhz implemented. I find itlwm to be more stable than airportitlwm at the moment

Ah I understand. So it's now it's just about waiting! 
I am grateful that there are developers out there working on projects like these.

**Comment by zombillano** [comment]
> Ah I understand. So now it's just about waiting!
> I am grateful that there are developers out there working on projects like these.
Yeah, it's just a matter of time. I'm pretty confident that they will keep improving and improving this project. They have been doing so much advancements in a relative short period of time
