### ISSUE TITLE
Rework of ACPI patches

### ISSUE THREAD

**Issue by EETagent** [EETagent/T480-OpenCore-Hackintosh#23]
MSzturc has most cleanest ACPI setup for ThinkPad I have ever seen. Especially things like XDSM, VDEV, etc.
I think that similar setup should be ported to this repo. 

https://github.com/simprecicchiani/Thinkpad-T460s-macOS-OpenCore/ which uses same patches has confirmed Windows support so this may fix #15

**Comment by EETagent** [comment]
Hi @MSzturc

I would like to ask about more information about SSDT-XDSM.aml. Why is there need to redirect to XDSM on non macOS systems? Does your DSDT include EXPx and IGBE ? Thanks for your time.

**Comment by MSzturc** [comment]
Im not sure if it's still needed. It was needed i've used xosi patching (otherwise i was not able to boot Windows 10) but now it could be that it's obsolete. Actually i would expect that's it's obsolete but since im completely of window right now and have no testbench for it it's still in the config. I would try without it

**Comment by benbender** [comment]
@EETagent HPET isn't used on newer Macbooks and can be disabled on my T480 simply by the following:

````


    External (HPTE, IntObj)
   
    //disable HPET
    Scope (\)
    {
        If (_OSI ("Darwin"))
        {
            HPTE = 0
        }
    }

````

**Comment by EETagent** [comment]
> @EETagent HPET isn't used on newer Macbooks and can be disabled on my T480 simply by the following:
> 
> ```
> 
> 
>     External (HPTE, IntObj)
>    
>     //disable HPET
>     Scope (\)
>     {
>         If (_OSI ("Darwin"))
>         {
>             HPTE = 0
>         }
>     }
> ```

Thanks, do you have any tip where to find if HPET is used on MBP 15,2?

**Comment by benbender** [comment]
@EETagent Sorry, but I don't get your question. Could you reiterate?

**Comment by EETagent** [comment]
@EETagent 

> HPET isn't used on newer Macbooks

I asked if you know if HPET is used on a MacBook Pro 15,12

**Comment by benbender** [comment]
Ah, sorry! Nope, it isn't. You can check for yourself here:
https://github.com/khronokernel/DarwinDumped/blob/master/MacBookPro/MacBookPro15%2C2/IORegistry/IOReg.txt

**Comment by EETagent** [comment]
I merged new-api branch, but will keep this open for suggestions. Will remove HPET in next commit
