### ISSUE TITLE
Replacing Wi-Fi card to Broadcom BCM94360CS2

### ISSUE THREAD

**Issue by ZedNait** [EETagent/T480-OpenCore-Hackintosh#26]
Hello

FYI, around 2 weeks ago I replaced in my T480 pre-installed Intel Wireless-AC 8265 to Broadcom BCM94360CS2 with NGFF adapter. It fits perfectly (photos below) and works in Hackintosh without problems too.
![IMG_3539](https://user-images.githubusercontent.com/13302457/91087003-cf74ab00-e660-11ea-8471-ebc01eef92c1.JPG)
![IMG_3545](https://user-images.githubusercontent.com/13302457/91086913-a48a5700-e660-11ea-80bb-5abf8349fbd9.JPG)
![IMG_3544](https://user-images.githubusercontent.com/13302457/91086954-b79d2700-e660-11ea-9e47-22c065179d22.JPG)
![IMG_3541](https://user-images.githubusercontent.com/13302457/91086996-cc79ba80-e660-11ea-895d-6e3da6a61fe7.JPG)
![Screenshot 2020-08-24 at 13 17 27](https://user-images.githubusercontent.com/13302457/91087019-d56a8c00-e660-11ea-9de5-da24528229aa.png)

**Comment by EETagent** [comment]
Thanks for posting success.

**Comment by swatchie-1** [comment]
> Hello
> 
> FYI, around 2 weeks ago I replaced in my T480 pre-installed Intel Wireless-AC 8265 to Broadcom BCM94360CS2 with NGFF adapter. It fits perfectly (photos below) and works in Hackintosh without problems too.
> ![IMG_3539](https://user-images.githubusercontent.com/13302457/91087003-cf74ab00-e660-11ea-8471-ebc01eef92c1.JPG)
> ![IMG_3545](https://user-images.githubusercontent.com/13302457/91086913-a48a5700-e660-11ea-80bb-5abf8349fbd9.JPG)
> ![IMG_3544](https://user-images.githubusercontent.com/13302457/91086954-b79d2700-e660-11ea-9e47-22c065179d22.JPG)
> ![IMG_3541](https://user-images.githubusercontent.com/13302457/91086996-cc79ba80-e660-11ea-895d-6e3da6a61fe7.JPG)
> ![Screenshot 2020-08-24 at 13 17 27](https://user-images.githubusercontent.com/13302457/91087019-d56a8c00-e660-11ea-9de5-da24528229aa.png)

Hi @ZedNait may I know how was your battery drain during sleep?
After I did this, power consumption during sleep was 1% per hour.
