### ISSUE TITLE
Freezing the screen after waking up from sleep

### ISSUE THREAD

**Issue by kai2ou** [EETagent/T480-OpenCore-Hackintosh#3]
How can to solve it?

**Comment by EETagent** [comment]
@kai2ou Thanks for your report.

What's your setup? Internal or external drive? Hibernation is still hit or miss, so try to disable it. 

Please provide crash report
 /Library/Logs /DiagnosticsReports

**Comment by kai2ou** [comment]
@EETagent 

[Kernel_2020-06-09-094644_KaideMacBook-Pro.gpuRestart.zip](https://github.com/EETagent/T480-OpenCore-Hackintosh/files/4749421/Kernel_2020-06-09-094644_KaideMacBook-Pro.gpuRestart.zip)

**Comment by kai2ou** [comment]
GPU with MX150

**Comment by EETagent** [comment]
@kai2ou  Dumb question, but MX150 is disabled? I don't know how to solve such problem. Maybe someone on Hackintosh Discord and subreddit will help. It's  probably GPU config issue, but try to disable AppleALC, there were problems when waking from sleep (which should be fixed now.)

**Comment by kai2ou** [comment]
- Solved, when disable MX150 GPU. 

add the following boot-arg
`boot-arg`

**Comment by EETagent** [comment]
Solved
