### ISSUE TITLE
Superb job, except...

### ISSUE THREAD

**Issue by inet777** [EETagent/T480-OpenCore-Hackintosh#31]
Everything works. Except RIGHT mouse press on Trackpad (i.e. mouse buttons work, but only LEFT mouse button works on Trackpad).

**Comment by inet777** [comment]
RIGHT mouse click on Trackpad appears as LEFT click on Trackpad.

**Comment by EETagent** [comment]
MacBooks doesn’t have right TrackPad button, for right click use double tap. There isn’t nothing wrong with this behavior. Or youse TrackPoint button.
