### ISSUE TITLE
ThinkPad USB-C/USB-A Hybrid Dock Gen 2 confirmed functional

### ISSUE THREAD

**Issue by slorent** [EETagent/T480-OpenCore-Hackintosh#34]
Just wanted to add that the ThinkPad USB-C/USB-A Hybrid Dock Gen 2 is functional.
I am using macOS Catalina 10.15.6 with version 5.0.1 of this OpenCore config and the MacbookPro15,2 SMBIOS.
To get external video output to work, the free DisplayLink Manager application is required.

TESTED AND WORKING:
* Primary USB-C;
* All USB-A ports;
* HDMI video output;
* Ethernet.

UNTESTED:
* Secondary USB-C;
* DisplayPort.

**Comment by EETagent** [comment]
Great to hear, will add to README. Please repost to #6 to have all issues organized.

BTW, Shouldn't video output on that dock be managed by DisplayPort Alt Mode? It is probably not wired to that HDMI port then.

**Comment by slorent** [comment]
I am not sure about the technical details behind the functioning of the video outputs on the dock, sorry. I simply used the HDMI port on the dock and it worked, that's all I can tell you 😄 If it's managed by DisplayPort Alt Mode, then I assume DisplayPort inputs on the dock should work too, right? I will repost this right away in that issue, thanks. Cheers!

**Comment by UA3** [comment]
Same result here with [Lenovo ThinkPad Hybrid (40AF)](https://www.lenovo.com/us/en/accessories-and-monitors/home-office/TP-Hybrid-USC-C-Dock-US/p/40AF0135US), once I installed [DisplayLink Manager](https://www.displaylink.com/downloads/macos) app both HDMI and DP started to work, I'll test more once I get back my T480 from the service center.

**Comment by EETagent** [comment]
Closing this issue, please continue in #6
