### ISSUE TITLE
Unable to access the system

### ISSUE THREAD

**Issue by kai2ou** [EETagent/T480-OpenCore-Hackintosh#35]
Hello.  @EETagent 
When I use the latest EFI, unable to access the system.

`panic(cpu 2 caller 0xffffff801ac469aa): Kernel trap at 0xffffff801b1b948f, type 14=page fault, registers:
CR0: 0x0000000080010033, CR2: 0x000000000000001c, CR3: 0x0000000489f8202c, CR4: 0x00000000003626e0
RAX: 0x000000000000f470, RBX: 0xffffff803f52c6a0, RCX: 0x0000000000000027, RDX: 0x0000000000000000
RSP: 0xffffff820ba8bbb0, RBP: 0xffffff820ba8bbb0, RSI: 0xffffff7f9b5be700, RDI: 0xffffff803f52c6a0
R8:  0x0000000000000027, R9:  0xffffff804275b990, R10: 0x0000000000000002, R11: 0xffffff820ba8bd50
R12: 0xffffff8041149920, R13: 0x0000000040512001, R14: 0xffffff7f9b5be700, R15: 0xffffff8041149920
RFL: 0x0000000000010202, RIP: 0xffffff801b1b948f, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x000000000000001c, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0, VF: 0

Backtrace (CPU 2), Frame : Return Address
0xffffff820ba8b610 : 0xffffff801ab1a65d 
0xffffff820ba8b660 : 0xffffff801ac54a75 
0xffffff820ba8b6a0 : 0xffffff801ac465fe 
0xffffff820ba8b6f0 : 0xffffff801aac0a40 
0xffffff820ba8b710 : 0xffffff801ab19d27 
0xffffff820ba8b810 : 0xffffff801ab1a117 
0xffffff820ba8b860 : 0xffffff801b2c1abc 
0xffffff820ba8b8d0 : 0xffffff801ac469aa 
0xffffff820ba8ba50 : 0xffffff801ac466a8 
0xffffff820ba8baa0 : 0xffffff801aac0a40 
0xffffff820ba8bac0 : 0xffffff801b1b948f 
0xffffff820ba8bbb0 : 0xffffff801b1b997f 
0xffffff820ba8bbe0 : 0xffffff801b199be2 
0xffffff820ba8bc00 : 0xffffff801b257d16 
0xffffff820ba8bc20 : 0xffffff7f9b5b6340 
0xffffff820ba8bc60 : 0xffffff801b253dda 
0xffffff820ba8bca0 : 0xffffff801b200e90 
0xffffff820ba8bd00 : 0xffffff801b25bc39 
0xffffff820ba8bd60 : 0xffffff801ac030af 
0xffffff820ba8bdb0 : 0xffffff801ab203c8 
0xffffff820ba8be10 : 0xffffff801aaf6d15 
0xffffff820ba8be70 : 0xffffff801ab0db22 
0xffffff820ba8bf00 : 0xffffff801ac2c065 
0xffffff820ba8bfa0 : 0xffffff801aac1226 
      Kernel Extensions in backtrace:
         com.apple.driver.AppleSMC(3.1.9)[AB612149-B321-3B95-8741-B99E79274FCD]@0xffffff7f9b5a9000->0xffffff7f9b5c7fff
            dependency: com.apple.driver.watchdog(1)[832CC890-EE61-33E0-8FD4-8D354BCD0921]@0xffffff7f9b5a0000
            dependency: com.apple.iokit.IOACPIFamily(1.4)[68557A36-4EE1-372A-983B-BB2769FDB8E0]@0xffffff7f9b509000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[DF219CC1-366A-31FC-B8ED-17C584BA2549]@0xffffff7f9b512000

BSD process name corresponding to current thread: powerd
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19G2021

Kernel version:
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
Kernel UUID: 1D3A0F3D-D908-397B-BD16-8F48C0823A2E
Kernel slide:     0x000000001a800000
Kernel text base: 0xffffff801aa00000
__HIB  text base: 0xffffff801a900000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 26084730162

`

**Comment by EETagent** [comment]
What is version you used previously?

**Comment by zombillano** [comment]
Did you replaced the whole EFI folder? Latest release includes OC 6.0.1 which includes some modifications. Please replace the whole EFI folder and then configure your config.plist file according with your serial/MB serial/etc/etc.

**Comment by kai2ou** [comment]
`panic(cpu 0 caller 0xffffff800df75997): "Zone cache element was used after free! Element 0xffffff8033fa29a0 was corrupted at beginning; Expected 0x86a783602078158a but found 0x1; canary 0x79587ce013823c2a; zone 0xffffff800e8a4220 (kalloc.16)"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.1/osfmk/kern/zcache.c:658
Backtrace (CPU 0), Frame : Return Address
0xffffff8200c1b920 : 0xffffff800df1a65d 
0xffffff8200c1b970 : 0xffffff800e054a75 
0xffffff8200c1b9b0 : 0xffffff800e0465fe 
0xffffff8200c1ba00 : 0xffffff800dec0a40 
0xffffff8200c1ba20 : 0xffffff800df19d27 
0xffffff8200c1bb20 : 0xffffff800df1a117 
0xffffff8200c1bb70 : 0xffffff800e6c1abc 
0xffffff8200c1bbe0 : 0xffffff800df75997 
0xffffff8200c1bc20 : 0xffffff800df71bff 
0xffffff8200c1bd50 : 0xffffff800df27584 
0xffffff8200c1bdc0 : 0xffffff800e59738c 
0xffffff8200c1bde0 : 0xffffff800e5973fa 
0xffffff8200c1be00 : 0xffffff800e5fe202 
0xffffff8200c1be40 : 0xffffff800e6068ad 
0xffffff8200c1bef0 : 0xffffff800e60649e 
0xffffff8200c1bf50 : 0xffffff800e608c56 
0xffffff8200c1bfa0 : 0xffffff800dec013e 

BSD process name corresponding to current thread: kernel_task
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19G2021

Kernel version:
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
Kernel UUID: 1D3A0F3D-D908-397B-BD16-8F48C0823A2E
Kernel slide:     0x000000000dc00000
Kernel text base: 0xffffff800de00000
__HIB  text base: 0xffffff800dd00000
System model name: MacBookPro15,2 (Mac-827FB448E656EC26)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 25478316756


`

**Comment by kai2ou** [comment]
> Did you replaced the whole EFI folder? Latest release includes OC 6.0.1 which includes some modifications. Please replace the whole EFI folder and then configure your config.plist file according with your serial/MB serial/etc/etc.

Yes, it is the whole EFI

**Comment by zombillano** [comment]
What's your setup? Please include SSD, model, etc, etc in order to track your issue. At least @EETagent and me are running latest version without any issue, your problem has to be related to your own particular setup.

**Comment by kai2ou** [comment]
i5 8350U, Samsung SSD 860 EVO 250GB, and MX 150(add `boot-arg:-wegnoegpu` to disable it)

**Comment by EETagent** [comment]
Must be a human error as many people use latest config and I don't know about any potential compatibility breaking change. You did not answered which version you used previously and if you replaced CPUFrienddataProvider so we can't help. If you replace whole EFI without any modification except replacing CPUFriendDataProvider it does not work? Do not forget to reset NVRAM.

**Comment by zombillano** [comment]
This has been abandoned for more than a week. I suggest to close it since OP doesn't seem to be responding any time soon. He may've solved its issue. If OP answers after issue close we can always reopen it.

**Comment by kai2ou** [comment]
I find the answer: it is the problem of NVMeFix.kext > 1.0.2
Only use the NVMeFix.kext <= 1.0.2 or disable it.
