### ISSUE TITLE
Sleep mode not working

### ISSUE THREAD

**Issue by MrSlowSheep** [EETagent/T480-OpenCore-Hackintosh#36]
Hello, I first all want to express my gratitude to the creator of this Github project. 
I am running macOS 10.15.6 and OpenCore 0.6.2. 
I downloaded all of the stuff from this GitHub and installed macOS yesterday. 
Everything works fine, just not the sleep/wake function.
If I put my laptop to sleep it just becomes a black screen and the laptop will become unresponsive. 
If I wait for macOS to automatically but the laptop in standby the only thing I can see is the mouse cursor on the top left corner. The screen is completely black. 

I have an i7-8650U, 32GB RAM, MX150, WiFI 8265 Card.
I set up my BIOS settings as on the GitHub instructions, I did generate my own SMBIOS but that's it. 
Am I supposed to install CPUFriend Power Management?

If you need more info please just let me know.

**Comment by zombillano** [comment]
What's the model of your SSD? Also, are you disabling your MX150 dGPU via config.plist file?

**Comment by MrSlowSheep** [comment]
Yup, disabling the MX150 did the trick! 
I just added "-wegnoegpu" to boot-args in my config.plist and now sleep/wake works perfectly.
My SSD is a "WDC PC SN720 SDAQNTW-512G-1001 Media".
