### ISSUE TITLE
Native or Emulated NVRAM?

### ISSUE THREAD

**Issue by MrSlowSheep** [EETagent/T480-OpenCore-Hackintosh#37]
I am following the guide to fix iServices over [https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#fixing-rom](dortania) but I have no idea if the NVRAM is native or emulated.
After logging with sudo in the terminal I type "sudo nvram -c" and the result I get is: "nvram: Error clearing firmware variables: (iokit/common) not permitted".
I tried searching around but I couldn't find an answer. Can anyone help me out please?

**Comment by zombillano** [comment]
I don't know whether if it is native or emulated but I can tell you that it works, imessage and icloud keys are getting stored just fine. I'm pretty sure you can skip the part related to NVRAM. In any case, always try with a disposable icloud account before introducing your real one.

**Comment by MrSlowSheep** [comment]
It seems like the T480 is using a native NVRAM anyway. 
I also followed the guide, but I still am having problems logging in. 
Actually two different accounts got blacklisted by Apple.
Since the NVRAM question I believe to be answered I will close this thread and open a new one if I still am encountering problems with iServices. 

Thank you!

**Comment by zombillano** [comment]
> It seems like the T480 is using a native NVRAM anyway.
> I also followed the guide, but I still am having problems logging in.
> Actually two different accounts got blacklisted by Apple.
> Since the NVRAM question I believe to be answered I will close this thread and open a new one if I still am encountering problems with iServices.
> 
> Thank you!

Mmmm I can successfully login to icloud and imessage, but I can't login to FaceTime on my hackintosh, but I can login just fine to all iservices on my macbook pro. Do you have any hint?

**Comment by MrSlowSheep** [comment]
The only thing I can suggest you doing is following the fixing iServices guide at the Dortania GitHub, and make sure that your config.plist is well configured about your en0. 
Also when trying to login on FaceTime, do you get an error with a code?

**Comment by zombillano** [comment]
> The only thing I can suggest you doing is following the fixing iServices guide at the Dortania GitHub, and make sure that your config.plist is well configured about your en0.
> Also when trying to login on FaceTime, do you get an error with a code?

Yes, I do get an error code. I don't really need iServices, I just wanted to know if our config over here is able to connect to iservices without any issue

**Comment by MrSlowSheep** [comment]
Well... you got your account blacklisted by Apple.
You will have to call their support to get it unlocked. They suggest adding a credit card to your Apple account before calling, to make it look less suspicious.

**Comment by MrSlowSheep** [comment]
> > The only thing I can suggest you doing is following the fixing iServices guide at the Dortania GitHub, and make sure that your config.plist is well configured about your en0.
> > Also when trying to login on FaceTime, do you get an error with a code?
> 
> Yes, I do get an error code. I don't really need iServices, I just wanted to know if our config over here is able to connect to iservices without any issue

BTW Sorry, I misunderstood your question.
Yes, I am unable to properly use Apple services with your config.plist. 
Sometimes it will automatically kick me out and I will have to login again several times. 
Most of the time the Apple store works but will not let me download anything. 

After this weekend I will contact Apple Support and try to get my account unlocked and I will report back.

**Comment by MrSlowSheep** [comment]
Okay so as many other people have reported: The account got blacklisted and needs to be fixed. 
Don't contact online chat as they can't help you with an issue like this.
Call Apple phone support and explain to them that you're afraid your account got blacklisted since you can't login to iMessages. 
They will ask you some account information and then will say that the account got fixed. 
It can take up to a business day though.

**Comment by EETagent** [comment]
@MrSlowSheep  Well, I actually have issues with iServices, mainly with iMessage ( I never used it on macOS and probably never would but it's nice to have everything working ). It does not show any error on Big Sur, but automatically sign me out after few seconds. After executing that app in Terminal, I see that scary error code suggesting calling Apple support. It's weird as I tried that with many new installations and SMBIOS and it did not work every time. After that I tried to login to our MacBook Air and iPad mini and everything was without problem.

Did you called them? Did they fixed your issue?

**Comment by MrSlowSheep** [comment]
> @MrSlowSheep Well, I actually have issues with iServices, mainly with iMessage ( I never used it on macOS and probably never would but it's nice to have everything working ). It does not show any error on Big Sur, but automatically sign me out after few seconds. After executing that app in Terminal, I see that scary error code suggesting calling Apple support. It's weird as I tried that with many new installations and SMBIOSes and it did not work every time. After that I tried to login to our MacBook Air and iPad mini and everything was without problem.
> 
> Did you called them? Did they fixed your issue?

Yes, I did call them right before the weekend.
They told me the problem would have been fixed in one business day. Yet I still have it.
I might have an iPod Touch lying around, so I will try logging in there and see if it works.

**Comment by MrSlowSheep** [comment]
> @MrSlowSheep Well, I actually have issues with iServices, mainly with iMessage ( I never used it on macOS and probably never would but it's nice to have everything working ). It does not show any error on Big Sur, but automatically sign me out after few seconds. After executing that app in Terminal, I see that scary error code suggesting calling Apple support. It's weird as I tried that with many new installations and SMBIOSes and it did not work every time. After that I tried to login to our MacBook Air and iPad mini and everything was without problem.
> 
> Did you called them? Did they fixed your issue?

Okay so I logged in on an iPod Touch I have found in the house and no, iMessages still won't work and is giving me back the same exact error code.
I suspect this is happening because of how the Wifi drivers are working compared to a real macOS device. At least that's my guess.
