### ISSUE TITLE
Hotkeys + Lid Sensor Laggy In Windows 10

### ISSUE THREAD

**Issue by swatchie-1** [EETagent/T480-OpenCore-Hackintosh#39]
Regarding the Hotkeys + Lid being laggy in Windows, i.e. takes 5 secs to 30 secs for my hotkeys and lid to respond (from FN + F4 to FN + F12 and also the Lid. Volume adjustment hotkeys are working fine). This is why whenever I close the lid, it takes from 5 secs to 30 secs for it to go to sleep in Windows because Windows doesn't register the sensor. 
However the Power button works fine. Pressing it will bring Windows to sleep and waking it up is also an instant when pressing it.

I've used Lenovo diagnostic tool in windows and discovered the lid sensor is not responsive. However in OS X, it works perfectly, including the hotkeys from F1 to F12.

I've completely wiped the PM981 again and re-installed windows again. This time I even created an EFI folder for this drive too. Which means I have an EFI folder for each of my SSD drives (mac and windows drive).

I thought it was Opencore's SSDT messing up my Windows hotkeys but re-installing windows again in a different drive and with its own EFI folder also does not solve this. 

Could this be due to the DSDT or SSDT tables being over-written?
If so, is there a way to revert it back?

**Comment by EETagent** [comment]
Sadly, it looks like issue with your machine. One option may be to reinstall UEFI from flash drive ( Modify CD image to be bootable using `geteltorito` tool, then downgrade and upgrade ) or to contact Lenovo support and fill warranty request. I do not know you country laws but generally ThinkPad warranty should not be void when disassembled.
