### ISSUE TITLE
Headphone jack sound issues

### ISSUE THREAD

**Issue by EETagent** [EETagent/T480-OpenCore-Hackintosh#4]
New issue dedicated to issue with headphone jack. Possible fix below. I will try to find out other options that do not require patching using bash scripts.

https://github.com/tienhuynh5312/ThinkPad-T480-Hackintosh
^ jack audio got fixed with above repo. But instead of running his provided "read and write.app", I executed:
`sudo mount -uw /`
then ./install.sh and reboot.

_Originally posted by @khokho in https://github.com/EETagent/T480-OpenCore-Hackintosh/issues/2#issuecomment-641109605_

**Comment by khokho** [comment]
Turns out this is an issue with layout-id. I just removed alcid=86 from boot-args and the value(layout_id=11) in DeviceProperties was already right for me(Realtek ALC257).

the guide I used: https://dortania.github.io/OpenCore-Desktop-Guide/post-install/audio.html

**Comment by khokho** [comment]
Not sure if the fix above is needed because I believe it is permament :D

**Comment by EETagent** [comment]
@khokho  Thanks

![obrazek](https://user-images.githubusercontent.com/20557318/84574706-91c5ed00-ada8-11ea-8e10-a0a28117e7c4.png)

Looks like I forgot to change value in Device Properties. layout-id 86 is created specially for T480. Could you test it with both boot-arg and right value in device properties?

**Comment by khokho** [comment]
![image](https://user-images.githubusercontent.com/6597974/84575023-5b459d80-adbb-11ea-9108-6f21d48bfb6e.png)
Actually right now I've only tested it with boot-args(alcid=11). Will test without it later.

I grabbed 11 from this page and it seemed to work. 
https://github.com/acidanthera/AppleALC/wiki/Supported-codecs

**Comment by EETagent** [comment]
I used layout-id 11 previously. When AppleALC 1.5.0 released, I moved layout-id to 86. To be honest, I haven't tested any of them as it was reported working for taina's build

**Comment by khokho** [comment]
Seems to be working without boot-args as well. It was really unusable before. I'll report if it goes weird again.

**Comment by khokho** [comment]
With id=11 there are still issues after sleep. id=14 does not work at all.

**Comment by EETagent** [comment]
Please test https://github.com/EETagent/T480-OpenCore-Hackintosh/commit/892183a2590cddc8326008c73003e3e54df422af

For me, audio jack and speakers works well. If it's everything right, will merge testing with master.

**Comment by EETagent** [comment]
@khokho Probably fixed. Reopen please if problems persists.
