### ISSUE TITLE
High power usage with Windows Hello Version of T480

### ISSUE THREAD

**Issue by whosdev** [EETagent/T480-OpenCore-Hackintosh#40]
First of all, I would like to thank you. I've used a lot of hackintosh, I've done a bit in the past, now I'm all but rusty, I thought that I would have a huge damn headache with Opencore, Catalina and everything. And then, I found your repo, perfect and well written, and damn, I've never done a hackintosh install as simple as this one with your config files. Everything works perfectly, performance wise, audio, even the intel wifi, which I didn't know it was possible back in the day. I just got this T480, with Windows Hello and FHD Touchscreen panel. I got this laptop yesterday, the battery life on windows was something closer to 6-7h maybe even a bit more (I didn't charge 100%), with the 48wh original battery (300-320 cycles it seems). But with hackintosh I'm not even getting 3 hours. Maybe 2 and a half. The only change I did after I copied the EFI folder was to switch the CPUFriendDataProvider with the 8350u version. Which is the one in my computer. Am I missing something? or maybe the USBmap is all wrong, and its causing the battery life to degrade this much?
Also, while hibernating it's also uncharging. I left it hibernating for 15 min, and decreased nearly 5%.
btw, I wouldn't put this up as an Issue, because it might be because of something that I didn't do or maybe the windows Hello feature. So if it really is because of it, I will delete the issue. Thanks again!

**Comment by zombillano** [comment]
Disable your IR camera on your BIOS and try again. The same if you have fingerprint sensor. Neither of them work under macOS and they are most likely the culprit of your battery issues.

**Comment by whosdev** [comment]
Already disabled it, the IR camera is the TPM security option, right? I didn't disabled the fingerprint in IO. I did it now.

**Comment by whosdev** [comment]
Also, wifi seems to stop working after 10-15minutes. When it happens, I need to disable the internet with heliport. But I guess it's a heliport or itlwm problem.

**Comment by zombillano** [comment]
> Already disabled it, the IR camera is the TPM security option, right? I didn't disabled the fingerprint in IO. I did it now.

I don't really know since I don't have the Windows Hello feature. You may be able to disable it at I/O screen. Give a try disabling your camera too. 

> Also, wifi seems to stop working after 10-15minutes. When it happens, I need to disable the internet with heliport. But I guess it's a heliport or itlwm problem.

I'm not using itlwm but airportitlwm, I'm going to try with the latest release of itlwm+heliport and report you back, but I didn't have any issue with itlwm + heliport in the past. Only bug I've found is that you can't use bluetooth microphone while using itlwm because it causes instabilities.

**Comment by whosdev** [comment]
Just read about the airportitlwm, it seems like its an evolution of the normal itlwm. I will try it as well, Is it stable enough?

**Comment by EETagent** [comment]
> or maybe the USBmap is all wrong,

USB map  is really different for machines with Windows IR camera, mainly SD Card, etc. Please create new one using USBMap.

>  Also, while hibernating it's also uncharging. I left it hibernating for 15 min, and decreased nearly 5%.

Hibernation means that laptop is shutdown and RAM is copied to persistent storage. If your laptop consumes power during hibernation, it's either not hibernating or there is a hardware issue

> . I will try it as well, Is it stable enough?

Yes, itlwm currently does not work on WPA Enterprise networks though.
