### ISSUE TITLE
Help wanted dual-battery

### ISSUE THREAD

**Issue by Juan-VC** [EETagent/T480-OpenCore-Hackintosh#41]
Hey, I am looking for someone with a dual-battery laptop that can help me get the other than the main battery working on macOS. Tried the acidanthera guide but I found it somewhat confusing and was not sure if did it correctly but did not work for me. Is it possible to get any help? I can attach the system's DSDT or any other table if needed. Thanks!

**Comment by EETagent** [comment]
macOS is not good at handeling two battery systems. Because of that, our batteries are using SSDT hotpatches merged into the one you see in the top bar

**Comment by Juan-VC** [comment]
Right, I am trying to implement both as one with hotpatches which did not work for. That is the main reason I am seeking for help!

**Comment by EETagent** [comment]
What exactly did not work? You see two batteries? You see one battery with half capacity?

Just copy over hotpatches in this repo, they are universal for all T480.

**Comment by Juan-VC** [comment]
Oh, I am looking to implement dual battery support for a Dell G7 7588. macOS find only one battery and shows a somewhat more than half capacity. 
<img width="852" alt="Screen Shot 2020-09-29 at 10 12 44 AM" src="https://user-images.githubusercontent.com/30065686/94584950-92da3780-023c-11eb-9faf-7998d1357145.png">
<img width="1552" alt="Screen Shot 2020-09-29 at 10 12 58 AM" src="https://user-images.githubusercontent.com/30065686/94584965-97065500-023c-11eb-9bc1-f1257153448f.png">

**Comment by EETagent** [comment]
Well, then I guess I can't help you. Patches that we use here are for ThinkPads only and it does not look like oc-little has one for you. Your best bet would be to ask at r/hackintosh and their Discord server, be prepared that it's possible that no one would help you there. Maybe try to completely remove all battery related patches and se how macOS handles that.

![image](https://user-images.githubusercontent.com/20557318/94585517-6a742c80-0280-11eb-9fdb-490d527914ce.png)

**Comment by zombillano** [comment]
I'll write in spanish so it is easy for us to comunicate: Tu mejor apuesta sería tratar de buscar algún grupo que se especialice en hackintosh para laptops Dell, normalmente hay similitudes entre distintos modelos de la misma marca. Por ejemplo, en el caso de las thinkpad hay gente trabajando en un kext llamado YogaSMC para poder portear muchas de las funcionalidades disponibles a nivel de OS en linux/windows.

La implementación en el caso de las thinkpad con doble batería es unificar ambas en una sola mediante parches ACPI, ya que no hay sentido alguno en hacer que macOS interprete dos baterías independientes, no cuenta con ningún tipo de software que permita hacer el manejo de ambas a nivel OS.

Sin embargo, al menos en el caso de las thinkpad el manejo de la carga/descarga de las baterías lo hace un EC, por lo que solo es necesario una interfaz que permita enviar los comandos correctos al EC (que es exactamente lo que se está haciendo con YogaSMC).

De cualquier forma, yo te recomendaría seguir lo hecho aqui: unifica ambas baterías mediante ACPI. 

Espero haberte ayudado.

**Comment by Juan-VC** [comment]
Thank you! I did understand the English explanation but the Spanish one was extended and very helpful. Once tried to unify both batteries in the ACPI tables and did not work so I am looking for help. Did not know there were some brand-specific Hackintosh groups, will try to find one for Dell laptops, and if I cannot find one will then seek help in Reddit or discord. Thanks again everyone, information is appreciated!
