### ISSUE TITLE
AirDrop not working - T480 w/ MX150

### ISSUE THREAD

**Issue by MrSlowSheep** [EETagent/T480-OpenCore-Hackintosh#42]
(MX150 disabled in config.plist)
Hello, I am running the GitHub configuration in my EFI folder with HeliPort.
I saw that some changes were made in the previous days, but to be honest I have no idea how to update my EFI stuff without screwing up.
AirDrop just won't open, or give me an error message about something missing.
Any idea why?

**Comment by zombillano** [comment]
> (MX150 disabled in config.plist)
> Hello, I am running the GitHub configuration in my EFI folder with HeliPort.
> I saw that some changes were made in the previous days, but to be honest I have no idea how to update my EFI stuff without screwing up.
> AirDrop just won't open, or give me an error message about something missing.
> Any idea why?

Airdrop doesn't work with itlwm at the moment. Only way to have airdrop and all alike features you will need to buy a broadcom card. Give a look at for tania's buying guide to choose one compatible.

**Comment by MrSlowSheep** [comment]
Ah I understand.
Thanks!
