### ISSUE TITLE
Ok to update to 10.15.7?

### ISSUE THREAD

**Issue by swatchie-1** [EETagent/T480-OpenCore-Hackintosh#44]
Anyone tried it yet and does it break compatibility?

**Comment by khokho** [comment]
I did it and it was absolutely smooth.

**Comment by benbender** [comment]
But be aware that there may be an ugly bug on apples side in 10.15.7: https://www.macrumors.com/guide/accountsd/

**Comment by swatchie-1** [comment]
Okay. I've updated and so far it's fine.

**Comment by benbender** [comment]
It also hit me after a while - so be aware and have an eye on your cpu usage ^^

**Comment by swatchie-1** [comment]
@benbender what did you do to solve it?

**Comment by benbender** [comment]
Reset everything icloud-related. PITA and I can't say what solved it finally....
