### ISSUE TITLE
How do I update the EFI folder from this project?

### ISSUE THREAD

**Issue by MrSlowSheep** [EETagent/T480-OpenCore-Hackintosh#46]
I see that recently some files over this project have been updated.
How do I update my EFI files without screwing up my current config?
After updating the files, do I have to somewhat update my config.plist?

**Comment by zombillano** [comment]
Most likely you will need to replace the whole EFI file and re-do all the changes that you made to your config.plist

**Comment by EETagent** [comment]
1) Backup your old EFI
2) Replace it with newer version
3) Port SMBIOS, kexts, your other changes to the old config.plist to the new one

**Comment by MrSlowSheep** [comment]
Okay so I am writing this for people that might have trouble finding SMBIOS information.
SMBIOS stuff is located in config.plist at PlatformInfo->Generic
If you have the nvidia MX150 do not forget to disable the GPU, by going to **boot-args** and adding "-wegnoegpu"

Also when migrating config.plist if you have followed the guide linked in this GitHub do not forget the en1 part, if you want iServices working properly. 

I will write an additional comment once I am done updating my EFI partition.

**Comment by MrSlowSheep** [comment]
>     1. Backup your old EFI
> 
>     2. Replace it with newer version
> 
>     3. Port SMBIOS, additional kexts, your other changes from the old config.plist to the new one
> 
> 
> It will take you only few minutes

Followed the instructions, everything is working fine.
Thank you for your help!
