### ISSUE TITLE
Battery Indicator Red 

### ISSUE THREAD

**Issue by MrSlowSheep** [EETagent/T480-OpenCore-Hackintosh#47]
So I updated my EFI folder and something weird is happening. 
If I put my laptop in sleep mode without the charging cable, and then I tun it on after several hours, the battery indicator goes red. The percentage is at 100%. After less than 5 minutes it drops to 20%.

Any idea why?

**Comment by EETagent** [comment]
That is weird. From what version you upgraded? To which version, or if from master to which commit?

**Comment by MrSlowSheep** [comment]
I am running Mac OS 10.15.7 with no problem.
I updated Open Core from 0.6.1 to 0.6.2 and all the other EFI files just by downloading everything included in the master of this project. 
I did not add anything else to my config.

**Comment by MrSlowSheep** [comment]
Also something popped up on the bios screen: 
OCS: No schema for DummyPowerManagement at 7 index, context <Quirks>!

**Comment by zombillano** [comment]
Do you mean you are getting something like this?:

![imagen](https://user-images.githubusercontent.com/34992400/95669179-22d48700-0b43-11eb-8a9b-e2e99492523a.png)

**Comment by MrSlowSheep** [comment]
Yes. And the battery indicator is red, even though it's 100%. 
This has never happened before, until I updated the EFI files.

**Comment by zombillano** [comment]
> Yes. And the battery indicator is red, even though it's 100%.
> This has never happened before, until I updated the EFI files.

It happens to me every now and then, but it solves itself after plugging and unplugging the charger. I think it is more like an annoying bug than harmful.

**Comment by benbender** [comment]
If its red, it indicates that SSDT-BATC thinks that one of your Battery is in "critical condition". If this happens sometimes, it may be a sign for a race-condition as the access to the EC is serialized via a MUTEX which, f.e., can timeout. If its constant, I would advice to check your battery with a OS which can handle two batteries natively (linux/ubuntu via usb-stick f.e.). You may have a failing battery in your system.

**Comment by MrSlowSheep** [comment]
@EETagent  Okay, I will do as you told me. Also it seems like, since updating the EFI, my laptop will often randomly wake up from sleep mode, even though I disabled the dGPU. This is what my current boot-args look like: `rtcfx_exclude=80-AB -wegnoegpu`.

ALso @benbender the batteries inside my T480 are draining faster than before, that's for sure.

**Comment by EETagent** [comment]
> 
> 
> @EETagent Okay, I will do as you told me. Also it seems like, since updating the EFI, my laptop will often randomly wake up from sleep mode, even though I disabled the dGPU. This is what my current boot-args look like: `rtcfx_exclude=80-AB -wegnoegpu`.
> 
> ALso @benbender the batteries inside my T480 are draining faster than before, that's for sure.

Are you sure that you have power nap disabled in preferences?

**Comment by benbender** [comment]
Again: To me it sounds like a broken battery. This surely needs immediate clearification. Cluttering this issue with various unrelated topics wont help either.

**Comment by EETagent** [comment]
Closed as stale
