### ISSUE TITLE
Latest commit does not boot on catalina

### ISSUE THREAD

**Issue by khokho** [EETagent/T480-OpenCore-Hackintosh#54]
Hello, 
last commit got stuck on apple logo before the progress bar. I've been using AirporItlwm before this with no problems so that shouldn't be an issue. Although I only had catalina version installed. I'll try booting using verbose mode when I have time.

**Comment by khokho** [comment]
Removing AirporItlwmBigSur and running OC snapshot in propertree fixes my issue.

**Comment by EETagent** [comment]
Yes, there was typo in config.plist. Fixed in 149bc905b533bdd2a81af273110b659555d6e076

Human error, but I still prefer to manually edit it.
