### ISSUE TITLE
Stuck at booting apple logo on T480 i7-8650U + nvidia MX150 

### ISSUE THREAD

**Issue by opatotto** [EETagent/T480-OpenCore-Hackintosh#61]
I'm trying to boot form USB to install Opencore, after the USB creation when I boot the screen shows me the apple logo but gets stuck at this point without the progress bar. Reading some related issues I think is due to the GPU Nvidia mx150 on t480 i7 models, do you guys know about this problem?

Edit: -wegnoegpu on boot-arg not working

**Comment by EETagent** [comment]
Try SSDT-OFFDGPU

https://github.com/EETagent/T480-OpenCore-Hackintosh/blob/yogasmc/OC/ACPI/SSDT-OFFDGPU.aml

**Comment by opatotto** [comment]
My bad, I removed some kexts files due to the native functionality of the fenvi wifi card: AirportItlwmBigSur.kext, AirportItlwmCatalina.kext, IntelBluetoothFirmware.kext, IntelBluetoothInjector.kext... forgot to remove them from my config.plist.

I'm using -wegnoegpu to deactivate my GPU and now I can boot and start the installation process, but after Big Sur is downloaded,my thinkpad reboots and can't pass this screen and keeps rebooting and I followed the UEFI settings:

![20201122_233201](https://user-images.githubusercontent.com/43834144/99934637-281d1800-2d24-11eb-9e65-073f6be8507f.jpg)
