### ISSUE TITLE
Sound distortion after Sleep

### ISSUE THREAD

**Issue by Charlyo** [EETagent/T480-OpenCore-Hackintosh#64]
Hey @EETagent! 

I didn't test audio earlier. It seems that after sleep on my T480 on yogasmc branch, audio is distorted (at least of youtube). Rebooting it solves the issue. 

Attaching an image with the installed kexts.
![installed_kexts](https://user-images.githubusercontent.com/7512047/101261076-b0dc8080-3734-11eb-836f-1dcc9341b4ff.png)

Thank you in advance!

**Comment by EETagent** [comment]
Hi @Charlyo 

Thanks for reporting. Couldn't this be a duplicate of #10?

Take a look at https://github.com/EETagent/T480-OpenCore-Hackintosh/issues/10#issuecomment-712126276

**Comment by Charlyo** [comment]
Sorry for the delay replying! @EETagent Tried the kext but didn't seem to solve the issue. Might have to take a look at the config file once I have more time.

**Comment by EETagent** [comment]
No need to apologize, I'm afraid I won't maintain this repository in the future. I completely moved my workspace to Fedora with GNOME. It combines everything I like on Aqua and Metro, and the programs I use are also for Linux ( For everything other, there is QEMU/Spice Windows VM ). So I actually lost the need to use macOS on my laptop

**Comment by Charlyo** [comment]
So sad to know that... Your repo was the one of the reasons I got with a T480 mainboard (untested) and therefore a T480. We will miss you around!

**Comment by EETagent** [comment]
They recently discussed same thing at a Clover T480 GitHub, and xma modified kernel extension called ComboJack to solve it. That probably applies only to audio jack part of this codec related issue though. As this sound exactly same like discussed in other, i would like to close it in favour of #10 

![obrazek](https://user-images.githubusercontent.com/20557318/103785875-052c9600-503c-11eb-9c59-73b1e92bd1b2.png)

**Comment by Charlyo** [comment]
Sure! It seems quite similar to what I'm experiencing.

**Comment by kai2ou** [comment]
How to solve it?

**Comment by kai2ou** [comment]
The problem is still exit in latest [0.6.7](https://github.com/EETagent/T480-OpenCore-Hackintosh/tree/OC067)

**Comment by kai2ou** [comment]
This problem only occurs when using battery
