### ISSUE TITLE
i just want to check if this is an issue with trackpoint, feel free to close (or i will, when i get an answer)

### ISSUE THREAD

**Issue by treeshateorcs** [EETagent/T480-OpenCore-Hackintosh#65]
okay, so this is a big deal for me, so i don't want to waste hours on installing and finding out that this does not work. basically the issue i had with virtually every hackintosh distro is with the trackpoint - when you middle click to scroll, it would paste the contents of the clipboard. so it was very hard to scroll, say, in a terminal window, it would just paste what's in the clipboard every time i tried to scroll. is this an issue here?

**Comment by TheQuetz** [comment]
Short answer: No, it isn't.

Long answer: That's how it works in several Linux distros, maybe that's why you are finding that behaviour, because most "drivers" (their proper name is kexts) are ported from their linux versions.

**Comment by treeshateorcs** [comment]
no, it's not how it works on linux. i have probably not made myself clear enough. on linux, when you middle click and tilt the nipple down or up it will scroll down or up. when you do the same on macos, it will first try to paste whatever there is in the clipboard and only then it will scroll down or up

btw i use arch

**Comment by treeshateorcs** [comment]
actually, nevermind, i'll just try to find a way to disable middle click paste altogether

**Comment by TheQuetz** [comment]
> no, it's not how it works on linux. i have probably not made myself clear enough. on linux, when you middle click and tilt the nipple down or up it will scroll down or up. when you do the same on macos, it will first try to paste whatever there is in the clipboard and only then it will scroll down or up
> 
> btw i use arch

That's a composed action. Apart from that, middle click doesn't paste the clipboard with the kexts used on this repo.

**Comment by treeshateorcs** [comment]
you mean does not paste at all? even intentionally? i mean when you just middle click, without tilting the nipple

**Comment by TheQuetz** [comment]
> you mean does not paste at all? even intentionally? i mean when you just middle click, without tilting the nipple

That's right.
