### ISSUE TITLE
Keyboard, Trackpad not working

### ISSUE THREAD

**Issue by dcbacarro** [EETagent/T480-OpenCore-Hackintosh#74]
Hi, I used your config to hack my Lenovo Thinkpad L480 laptop. Most parts work, but I can't make the keyboard and trackpad to work. Can you please help me?

**Comment by EETagent** [comment]
L480 uses Elantech TrackPad, VoodooRMI used here is for models with Synaptics only

Keyboard should work just fine with VoodooPS2, there must be another issue
