### ISSUE TITLE
Question: Fix for Bluetooth/Wireless on T470 ?

### ISSUE THREAD

**Issue by jmarsil** [EETagent/T480-OpenCore-Hackintosh#75]
Hey managed to get most everything working that you've described using your repo and some modifications to handle the following specs. However, Bluetooth and wireless don't seem to work. Do you have some suggestions and/or a potential fix?

Lenovo T470 PF14JVHR

Processor
1x Intel Core i5-6300U Processor()
Memory
1x 16GB DDR4-2133
Hard Drive
1x 256GB OPAL2.0
Wireless Network
1x Intel Wireless 8260(2x2AC) with BT4.1
Ports
1x HDMI
Camera
1x 720p HD Camera with MIC
Graphics
1x Intel HD 520
Monitor
Multitouch

**Comment by kai2ou** [comment]
[https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.3.0-alpha](url)
Test the latest kext

**Comment by EETagent** [comment]
Wi-Fi should just work, try latest itlwm. Bluetooth also depends on right USB port configuration.

Also, it might be because of Windows #73

**Comment by jmarsil** [comment]
Cool I'll check that out and see if it works. For the latest itlwm, should I update the KTEXT folder and restart? Or reinstall everything? @EETagent

**Comment by EETagent** [comment]
You should download right version for your OS and rename it to match current naming in my config.plist if you did not changed that

**Comment by jmarsil** [comment]
Did that and updated the mounted EFI folder, but did not work. Do you have any idea of anything else I should change/check that could fix it? Would re-installing work? @EETagent

**Comment by EETagent** [comment]
https://openintelwireless.github.io/itlwm/Troubleshooting.html#kernel-extension-loading-status

**Comment by jmarsil** [comment]
Still doesn't seem to be working. I think it might be a USB mapping issue. Is there a specific ktext/ACPI file you modified/used for mapping T480 ports?

**Comment by EETagent** [comment]
We use [SSDT-XHC](https://github.com/EETagent/T480-OpenCore-Hackintosh/blob/master/Other/Disassembled%20ACPI/SSDT-XHC.dsl) from benbender for native USB support on xx80 series ThinkPads.

As T470 is not probably supported, you should make your own USB mapping using USBMap, etc.
