### ISSUE TITLE
big sur installation does not boot 

### ISSUE THREAD

**Issue by vortck** [EETagent/T480-OpenCore-Hackintosh#76]
pretty much title. the big sur recovery OS boots just fine and i can install macOS 11, but when i actually try to boot from said installation my computer reboots and i see the kernel panic screen

catalina works perfectly fine for me though 

what causes this?

laptop specs are i5 8250U, 16GB DDR4, intel 512GB NVMe SSD

**Comment by TheQuetz** [comment]
Disable AppleBacklightSmoother.kext, it has issues with latest big sur release. Faced the same yesterday and that fixed it.

**Comment by vortck** [comment]
> Disable AppleBacklightSmoother.kext, it has issues with latest big sur release. Faced the same yesterday and that fixed it.

awesome, i’ll try this, thanks!

**Comment by EETagent** [comment]
https://github.com/hieplpvip/AppleBacklightSmoother/issues/12

It seems like WEG 1.4.6 made some API changes and AppleBacklightSmoother causes KP because of that. Going to remove it in next update

**Comment by whosdev** [comment]
I tried to remove the AppleBacklightSmoother.kext, but it still didn't work. I only removed the file, Do I need to do something else?

**Comment by zombillano** [comment]
> I tried to remove the AppleBacklightSmoother.kext, but it still didn't work. I only removed the file, Do I need to do something else?

Disable the kext on the config.plist file in your efi folder

**Comment by EETagent** [comment]
This issue is already fixed in master, closing
