### ISSUE TITLE
Unable to boot MacOs Big Sur without usb

### ISSUE THREAD

**Issue by lazarvgd** [EETagent/T480-OpenCore-Hackintosh#83]
I installed today BigSur without any problem, but if I remove usb flash drive it won't boot. If I put back the usb it shows me the same screen when Option key is held and I can choose MacOs to boot. Currently I do not have any other problem than this one... Any advice how to fix this? Thanks

**Comment by gabgabe** [comment]
Did you copy your efi folder to your efi disk partition?

**Comment by lazarvgd** [comment]
> Did you copy your efi folder to your efi disk partition?

I did not, to be honest I only found that it needs to be copied to the flash drive , but not to the disk. Can you please give me a reference to this?

Thanks

**Comment by gabgabe** [comment]
You're missing some basics as some guides assumes you already know.

Google how to mount efi partition, then just clone your efi usb folder to your disk efi partition. 

Generally if you can correctly boot the OS via usb, then you can boot via disk and viceversa. I always keep a usb pendrive with a working efi configuration in case I have any problem on main disk so I can boot and fix the mess.

Honestly I still use an old clover software version I've installed years ago just for mounting EFI 😅 but there are various ways to mount a boot partition.

Regards

**Comment by lazarvgd** [comment]
> You're missing some basics as some guides assumes you already know.
> 
> Google how to mount efi partition, then just clone your efi usb folder to your disk efi partition.
> 
> Generally if you can correctly boot the OS via usb, then you can boot via disk and viceversa. I always keep a usb pendrive with a working efi configuration in case I have any problem on main disk so I can boot and fix the mess.
> 
> Honestly I still use an old clover software version I've installed years ago just for mounting EFI 😅 but there are various ways to mount a boot partition.
> 
> Regards

Thank you very much, I did not realized that there is EFI partition that needs to be filled with the same efi from the flash drive.
It works! Thank you!
