### ISSUE TITLE
Bluetooth is not working (also, docking station/dual displays does not seem to work)

### ISSUE THREAD

**Issue by fabiandiez** [EETagent/T480-OpenCore-Hackintosh#9]
Hi.

First of all, thank you for creating sharing and maintaining this OpenCore config! I managed to get a lot of thinks working with it.

I still have some issues with bluetooth however:
![Screenshot 2020-06-23 at 00 05 06](https://user-images.githubusercontent.com/47107890/85339820-3355e880-b4e5-11ea-98e6-8ba6d1eccc4f.png)

Also, I cant get my dual monitor setup to work using the official Lenovo Docking Station.
Depending on the combination of ports and and cables I use, I can get either only one of the displays working, or the OS recognises them, but not independently (meaning I can only access a single display via the System Preferences), so I always have a mirrored view.
Any help or hint in the right direction would be greatly appreciated, and again, thank you for your time and effort!

**Comment by EETagent** [comment]
Thanks for testing. 

1) Bluetooth mostly works for me, there are few boots when it don't. Do you run Windows aside from macOS? If yes, then the reason why this happens is that Windows preaches things like BT for faster boot. Please check if Bluetooth is listed under USB section of System profile.
2) I do not have docking station, so I can't help you much with it. Is it Thunderbolt one, USB A one? It the latter, it is  needed to make custom USB map, so docking station could work.

**Comment by fabiandiez** [comment]
Hi, thanks for responding.

I do not run Windows, I am currently only booting macOS. 

Here is my USB section with no additional devices connected:

> USB 3.0 Bus:
>
>  Host Controller Driver:	AppleUSBXHCISPTLP
>  PCI Device ID:	0x9d2f 
>  PCI Revision ID:	0x0021 
>  PCI Vendor ID:	0x8086 
>
>  USB3.0-CRW:
>
>  Product ID:	0x0316
>  Vendor ID:	0x0bda  (Realtek Semiconductor Corp.)
>  Version:	2.04
>  Serial Number:	20120501030900000
>  Speed:	Up to 5 Gb/s
>  Manufacturer:	Generic
>  Location ID:	0x14700000 / 44
>  Current Available (mA):	900
>  Current Required (mA):	800
>  Extra Operating Current (mA):	0
>
> Vendor-Specific Device:
>
>  Product ID:	0x009a
>  Vendor ID:	0x06cb  (Synaptics Inc.)
>  Version:	1.64
>  Serial Number:	7162a40765d2
>  Speed:	Up to 12 Mb/s
>  Location ID:	0x14600000 / 41
>  Current Available (mA):	500
>  Extra Operating Current (mA):	0
>  Built-In:	Yes
>
> Integrated Camera:
>
>  Product ID:	0x2113
>  Vendor ID:	0x5986
>  Version:	54.23
>  Speed:	Up to 480 Mb/s
>  Manufacturer:	SunplusIT Inc
>  Location ID:	0x14500000 / 42
>  Current Available (mA):	500
>  Current Required (mA):	500
>  Extra Operating Current (mA):	0
>  Built-In:	Yes
>
> L830-EB:
>
>  Product ID:	0x0210
>  Vendor ID:	0x2cb7
>  Version:	3.33
>  Serial Number:	004999010640000
>  Speed:	Up to 480 Mb/s
>  Manufacturer:	FIBOCOM
>  Location ID:	0x14400000 / 60
>  Current Available (mA):	500
>  Current Required (mA):	100
>  Extra Operating Current (mA):	0
>  Built-In:	Yes

> USB 3.1 Bus:
>
>  Host Controller Driver:	AppleUSBXHCIAR
>  PCI Device ID:	0x15c1 
>  PCI Revision ID:	0x0001 
>  PCI Vendor ID:	0x8086 

I've ensured that bluetooth is working by live-booting Manjaro Linux, everything works fine there.
Does your configuration show an actual bluetooth device?


The docking station uses thunderbolt. I can connect additional USB devices just fine, only the display support seems to be an issue.
I've tried creating a custom USB map using corpnewt's USBmap tool but without much success (I can get USB/Camera etc. working, but the macOS still registers multiple displays as one).

**Comment by EETagent** [comment]
@fabiandiez  
` Manufacturer: FIBOCOM` 
` Vendor ID: 0x06cb (Synaptics Inc.)`

Your USB map is different, you have WLAN card, BT is missing and fingerprint reader should not be there. Remove USBMap.kext and add USBInjectAll, then slowly try to remap it. BT should be there

Not sure if DisplayPort alt mode is somewhat connected to the Thunderbolt here. It is possible as bad Thunderbolt microcode caused completely broken USB C port on ThinkPads. Are you hot-plugging it or already booting with dock connected?

**Comment by fabiandiez** [comment]
I tried creating a custom keymap using the USBmap tool provided by corpnewt, but bluetooth does not show up there either:
![Screenshot 2020-06-23 at 23 55 17](https://user-images.githubusercontent.com/47107890/85469197-a9be1d80-b5ad-11ea-8063-10a5ea26080b.png)
I also tried using Hackintool's USB functionality, but again, no bluetooth adapter.

I have tried both hot-plugging as well as booting with the dock connected, same result.

**Comment by zombillano** [comment]
I'm not getting any problems with bluetooth at all, I can pair my earpods without any trouble at any time... What's your WiFi card? Mine is Intel AC8265. Here is what is shown on system information: 

![imagen](https://user-images.githubusercontent.com/34992400/85477767-93e63380-b580-11ea-81ae-fb93243d8976.png)

Are you able to hotplug your dock without any trouble? What do you see on IORegistryExplorer when you have your dock connected?

**Comment by zombillano** [comment]
Sorry for double posting. Your dock problem could be something related purely on Mac OS and not this OpenCore config. You can try what's proposed over here: https://forums.lenovo.com/t5/Displays-Options-and-Accessories/ThinkPad-Thunderbolt-3-Dock-with-Macbook-Pro-Touchbar/m-p/3815715?page=3

**Comment by fabiandiez** [comment]
I have the AC8265 too. Hot-plugging the dock works without any issues.
I don't have a lot of experience using the IORegistryExplorer, what exactly should I be looking for?

Im starting to get a feeling that both the bluetooth and the docking station issue might actually be macOS related, as that would be the only way to explain the difference between our setups.

I might reinstall macOS if I have the time. I'll keep you updated.

**Comment by zombillano** [comment]
Insteresting enough, since I always believed that you would need some special kext to make thunderbolt hotplug work. You should be looking for your thunderbolt dock at IORegistryExplorer and what it detects (USB ports, ethernet, DP, etc).

I'm using macOS 15.5.5, are you using the same one?. I saw at the page that I linked that you might need to download a driver called display link to make display ports work as expected under macOS.

**Comment by fabiandiez** [comment]
Ok I'll try to do that when I get back home.

I am using 10.15.5, are you sure thats not what you meant?
I've tried installing the display link driver, but that didn't help unfortunately (however, my trackpad stopped working so I had to remove the driver).

**Comment by fabiandiez** [comment]
This is my IGPU tree after connecting and disconnecting from the docking station.

![Screenshot 2020-06-24 at 23 11 15](https://user-images.githubusercontent.com/47107890/85628392-5fea3b80-b670-11ea-8c18-76dbc7bda298.png)

**Comment by fabiandiez** [comment]
Well, I guess I can close this for now. I ended up buying a bluetooth dongle from Amazon. The default docking station might not support dual displays, even with the offical drivers.
